---
version: v1
plugins:
  - name: openapiv2
    out: ./protos/generated/swagger
    opt:
      - logtostderr=true
      - grpc_api_configuration=protos/sources/data-node/grpc-rest-bindings.yml
      - grpc_api_configuration=protos/sources/vega/grpc-rest-bindings.yml
  - name: doc
    out: ./protos/generated/grpc
    opt:
      - json
      - proto.json
    strategy: all
