# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

[API]
  Level = 0
  GraphQLServerIpAddress = "127.0.0.1"
  GraphQLServerPort = 3004
  GrpcServerIpAddress = "127.0.0.1"
  GrpcServerPort = 3002
  RestProxyIpAddress = "127.0.0.1"
  RestProxyServerPort = 3003

[Blockchain]
  Level = -1
  ClientAddr = "tcp/://0.0.0.0:26657"
  ClientEndpoint = "26658"
  ServerAddr = "localhost"
  ServerPort = 46658
  LogOrderAmendDebug = true
  LogOrderCancelDebug = true
  LogOrderSubmitDebug = true
  LogTimeDebug = true

[Candles]
  Level = 0

[Execution]
  Level = 0

[Logging]

[Markets]
  Level = 0

[Matching]
  Level = 0
  LogPriceLevelsDebug = false
  LogRemovedOrdersDebug = false
  ProRataMode = false

[Orders]
  Level = 0

[Parties]
  Level = 0

[Risk]
  Level = 0
  PyRiskModelAbsolutePath = false
  PyRiskModelDefaultFileName = "/risk-model.py"
  PyRiskModelLongIndex = 1
  PyRiskModelShortIndex = 0

[Storage]
  Level = 0
  CandleStoreDirPath = "../../data/candlestore"
  LogPositionStoreDebug = false
  OrderStoreDirPath = "../../data/orderstore"
  TradeStoreDirPath = "../../data/tradestore"

[Time]
  Level = 0

[Trades]
  Level = -1
