[API]
  Level = 0
  Timeout = 5000
  GraphQLServerPort = 3004
  GraphQLServerIpAddress = "0.0.0.0"
  GraphQLSubscriptionRetries = 3
  RestProxyServerPort = 3003
  RestProxyIpAddress = "0.0.0.0"
  GrpcServerPort = 3002
  GrpcServerIpAddress = "0.0.0.0"
  GrpcSubscriptionRetries = 3

[Blockchain]
  Level = 0
  ClientAddr = "tcp://0.0.0.0:26657"
  ClientEndpoint = "/websocket"
  ServerPort = 26658
  ServerAddr = "localhost"
  LogTimeDebug = true
  LogOrderSubmitDebug = true
  LogOrderAmendDebug = false
  LogOrderCancelDebug = false

[Candles]
  Level = 0

[Execution]
  Level = 0
  [Execution.Markets]
    Path = "/Users/jeremy/.vega/markets"
    Configs = ["BTCDEC19.json", "ETHJUN19.json", "EURMAR20.json"]
  [Execution.Engines]
    Level = 0
    [Execution.Engines.Matching]
      Level = 0
      LogPriceLevelsDebug = false
      LogRemovedOrdersDebug = false
    [Execution.Engines.Risk]
      Level = 0
      LogMarginUpdate = true
    [Execution.Engines.Position]
      Level = 0
      LogPositionUpdate = true
    [Execution.Engines.Settlement]
      Level = 0
    [Execution.Engines.Collateral]
      Level = 0
      CreateTraderAccounts = true

[Logging]
  Environment = "dev"
  [Logging.Custom]
    [Logging.Custom.Zap]
      Level = -1
      Development = true
      Encoding = "console"
      OutputPaths = ["stdout"]
      ErrorOutputPaths = ["stderr"]
    [Logging.Custom.ZapEncoder]
      CallerKey = "C"
      EncodeCaller = "short"
      EncodeDuration = "string"
      EncodeLevel = "capital"
      EncodeName = "full"
      EncodeTime = "iso8601"
      LevelKey = "L"
      LineEnding = "\n"
      MessageKey = "M"
      NameKey = "N"
      TimeKey = "T"

[Markets]
  Level = 0

[Orders]
  Level = 0

[Parties]
  Level = 0

[Risk]
  Level = 5
  PyRiskModelAbsolutePath = false
  PyRiskModelDefaultFileName = "/risk-model.py"
  PyRiskModelShortIndex = 0
  PyRiskModelLongIndex = 1

[Storage]
  Level = 0
  OrderStoreDirPath = "/Users/jeremy/.vega/orderstore"
  TradeStoreDirPath = "/Users/jeremy/.vega/tradestore"
  CandleStoreDirPath = "/Users/jeremy/.vega/candlestore"
  MarketStoreDirPath = "/Users/jeremy/.vega/marketstore"
  LogPositionStoreDebug = false
  Timeout = "5s"

[Trades]
  Level = 0

[Time]
  Level = 0

[Monitoring]
  Level = 0
  IntervalMilliseconds = 500
  Retries = 5

[Pprof]
  Level = 0
  Enabled = false
  Port = 6060
  ProfilesDir = "/tmp"
