[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/tendermint/tendermint"
  branch = "master"

[[override]]
  name = "github.com/golang/protobuf"
  version = "=1.1.0"

[[override]]
  name = "google.golang.org/grpc"
  version = "=1.13.0"

[[constraint]]
  branch = "master"
  name = "github.com/tav/golly"

[[override]]
  name = "github.com/dgraph-io/badger"
  version = "=1.5.3"

[[constraint]]
  name = "github.com/99designs/gqlgen"
  branch = "master"
