---

name: "Add Issues To Project Board"

"on":
  issues:
    types: [opened]

jobs:
  add_issue:
    runs-on: ubuntu-latest
    steps:
      - name: "Add issue project board"
        env:
          GH_TOKEN: ${{ secrets.GH_NEW_CARD_TO_PROJECT }}
          PROJECT_ID: ${{ secrets.CORE_PROJECT_ID }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
          USER: "MDQ6VXNlcjgzNTEwMTQ4"
        run: |
          gh api graphql -f query='
            mutation($project:ID!, $issue:ID!) {
              addProjectV2ItemById(input: {projectId: $project, contentId: $issue, clientMutationId: $user}) {
                item {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f issue=$ISSUE_ID -f user=$USER
