---

name: Release

"on":
  push:
    # tags:
    # - 'v*'
    branches: [ 1595-build-vega-binaries-for-multiple-platforms ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.11.13
        id: go
        uses: actions/setup-go@v1
        with:
          go-version: 1.11.13

      - name: Check out
        uses: actions/checkout@v2

      - name: Build
        id: build
        # default shell: bash --noprofile --norc -eo pipefail {0}
        shell: bash --noprofile --norc -exo pipefail {0}
        env:
          GOPATH: /home/runner/go
          DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # The following git+ssh config enables accessing private github repos.
          git config --global url."git@github.com:vegaprotocol".insteadOf "https://github.com/vegaprotocol"
          mkdir -p -m 0700 ~/.ssh
          ssh-keyscan github.com 1>~/.ssh/known_hosts 2>/dev/null ; chmod 0644 ~/.ssh/known_hosts
          if ! echo "${DEPLOY_SSH_PRIVATE_KEY}" | grep -q "BEGIN [A-Z]* PRIVATE KEY" ; then
            echo "Need env var DEPLOY_SSH_PRIVATE_KEY to have a private key" ; exit 1
          fi
          echo "${DEPLOY_SSH_PRIVATE_KEY}" >~/.ssh/id_rsa ; chmod 0600 ~/.ssh/id_rsa
          unset DEPLOY_SSH_PRIVATE_KEY

          # The following config adds tools
          mkdir -p "$GOPATH/src/tmpproject"
          pushd "$GOPATH/src/tmpproject" 1>/dev/null
          go get github.com/vegaprotocol/modvendor@v0.0.2
          export PATH="$PATH:$GOPATH/bin/modvendor"
          command -v modvendor
          popd 1>/dev/null

          # Now build
          make deps
          make test
          make build-linux-amd64 build-linux-386

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cmd/*/*-linux-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
